/**
 * Table de repli des créatures.
 *
 * `packages/engine` ne peut pas dépendre de `@auvergne/content` (dépendance
 * inverse : c'est le contenu qui dépend du moteur). Le combat lit donc les
 * définitions via le pont `content.ts`, que l'intégrateur alimente au démarrage
 * avec les vraies données de contenu.
 *
 * Cette table est le **repli** utilisé tant qu'aucun fournisseur n'est branché
 * (tests unitaires du moteur, simulations hors client). Elle reprend les
 * statistiques de prototype du document maître (§5.1 et §5.2) et n'est jamais
 * consultée dès que `setCombatContent` a été appelé avec une créature connue.
 */

import type { CreatureAbility, CreatureDef, CreatureId, FactionId } from '../types.js';

interface Spec {
  id: CreatureId;
  faction: FactionId;
  tier: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  upgraded: boolean;
  upgradeOf?: CreatureId;
  name: string;
  namePlural: string;
  hp: number;
  attack: number;
  defense: number;
  dmgMin: number;
  dmgMax: number;
  speed: number;
  initiative?: number;
  growth: number;
  size?: 1 | 2;
  flying?: boolean;
  shooter?: boolean;
  shots?: number;
  abilities?: CreatureAbility[];
  lore: string;
}

const TIER_POWER: Record<number, number> = {
  1: 45,
  2: 120,
  3: 260,
  4: 540,
  5: 1150,
  6: 2500,
  7: 6200,
};

const TIER_COST: Record<number, number> = {
  1: 60,
  2: 130,
  3: 260,
  4: 500,
  5: 1000,
  6: 1900,
  7: 4200,
};

function build(s: Spec): CreatureDef {
  const power = Math.floor((TIER_POWER[s.tier] * (s.upgraded ? 122 : 100)) / 100);
  const gold = Math.floor((TIER_COST[s.tier] * (s.upgraded ? 130 : 100)) / 100);
  const cost: CreatureDef['cost'] = { ecus: gold };
  if (s.tier >= 4) cost.fer = s.tier - 3;
  if (s.tier >= 6) {
    if (s.faction === 'granit') cost.filDor = s.tier - 5;
    else cost.essence = s.tier - 5;
  }
  const def: CreatureDef = {
    id: s.id,
    faction: s.faction,
    tier: s.tier,
    upgraded: s.upgraded,
    name: s.name,
    namePlural: s.namePlural,
    hp: s.hp,
    attack: s.attack,
    defense: s.defense,
    dmgMin: s.dmgMin,
    dmgMax: s.dmgMax,
    speed: s.speed,
    initiative: s.initiative ?? s.speed,
    growth: s.growth,
    cost,
    power,
    size: s.size ?? (s.tier >= 5 ? 2 : 1),
    abilities: s.abilities ?? [],
    lore: s.lore,
  };
  if (s.upgradeOf) def.upgradeOf = s.upgradeOf;
  if (s.flying) def.flying = true;
  if (s.shooter) {
    def.shooter = true;
    def.shots = s.shots ?? 10;
  }
  return def;
}

const SPECS: Spec[] = [
  /* ───────────────────────── Châtellenie de Granit ──────────────────────── */
  {
    id: 'granit_t1',
    faction: 'granit',
    tier: 1,
    upgraded: false,
    name: 'Manant',
    namePlural: 'Manants',
    hp: 4,
    attack: 2,
    defense: 2,
    dmgMin: 1,
    dmgMax: 2,
    speed: 4,
    growth: 18,
    lore: "Levée des villages de la vallée : fourche, gambison de chanvre et une obstination de granit.",
  },
  {
    id: 'granit_t1_up',
    faction: 'granit',
    tier: 1,
    upgraded: true,
    upgradeOf: 'granit_t1',
    name: 'Franc-Serf',
    namePlural: 'Francs-Serfs',
    hp: 6,
    attack: 3,
    defense: 4,
    dmgMin: 1,
    dmgMax: 3,
    speed: 4,
    initiative: 5,
    growth: 18,
    abilities: [{ kind: 'retaliations', count: 2 }],
    lore: "Affranchi par charte comtale, il tient la ligne parce que la ligne est désormais la sienne.",
  },
  {
    id: 'granit_t2',
    faction: 'granit',
    tier: 2,
    upgraded: false,
    name: 'Gabelou',
    namePlural: 'Gabelous',
    hp: 12,
    attack: 5,
    defense: 6,
    dmgMin: 2,
    dmgMax: 4,
    speed: 5,
    growth: 12,
    abilities: [{ kind: 'slow_on_hit', bp: 1000 }],
    lore: "Commis du sel, bâton ferré et registre : il compte, il pèse, il retient.",
  },
  {
    id: 'granit_t2_up',
    faction: 'granit',
    tier: 2,
    upgraded: true,
    upgradeOf: 'granit_t2',
    name: 'Prévôt du Sel',
    namePlural: 'Prévôts du Sel',
    hp: 15,
    attack: 7,
    defense: 8,
    dmgMin: 2,
    dmgMax: 5,
    speed: 5,
    initiative: 6,
    growth: 12,
    abilities: [
      { kind: 'slow_on_hit', bp: 1500 },
      { kind: 'zone_of_control' },
    ],
    lore: "Nul ne franchit la limite de gabelle sans s'expliquer devant lui.",
  },
  {
    id: 'granit_t3',
    faction: 'granit',
    tier: 3,
    upgraded: false,
    name: 'Arbalétrier des Farges',
    namePlural: 'Arbalétriers des Farges',
    hp: 20,
    attack: 8,
    defense: 6,
    dmgMin: 4,
    dmgMax: 7,
    speed: 5,
    growth: 8,
    shooter: true,
    shots: 12,
    abilities: [{ kind: 'slow_on_hit', bp: 500 }],
    lore: "Le carreau part sans bruit d'avertissement ; c'est toute sa doctrine.",
  },
  {
    id: 'granit_t3_up',
    faction: 'granit',
    tier: 3,
    upgraded: true,
    upgradeOf: 'granit_t3',
    name: 'Maître-Arbalétrier',
    namePlural: 'Maîtres-Arbalétriers',
    hp: 24,
    attack: 10,
    defense: 8,
    dmgMin: 5,
    dmgMax: 9,
    speed: 5,
    initiative: 6,
    growth: 8,
    shooter: true,
    shots: 14,
    abilities: [
      { kind: 'pierce_defense', bp: 2000 },
      { kind: 'slow_on_hit', bp: 800 },
      { kind: 'range_penalty_immune' },
    ],
    lore: "Il connaît la portée de chaque chemin creux entre les Farges et Bise.",
  },
  {
    id: 'granit_t4',
    faction: 'granit',
    tier: 4,
    upgraded: false,
    name: "Grenadière d'Or",
    namePlural: "Grenadières d'Or",
    hp: 34,
    attack: 10,
    defense: 12,
    dmgMin: 6,
    dmgMax: 10,
    speed: 6,
    growth: 6,
    abilities: [{ kind: 'morale_aura', value: 1 }],
    lore: "Brodeuse au fil d'or ; l'emblème de grenade qu'elle coud redresse les échines.",
  },
  {
    id: 'granit_t4_up',
    faction: 'granit',
    tier: 4,
    upgraded: true,
    upgradeOf: 'granit_t4',
    name: "Dame au Fil d'Or",
    namePlural: "Dames au Fil d'Or",
    hp: 40,
    attack: 12,
    defense: 14,
    dmgMin: 7,
    dmgMax: 12,
    speed: 7,
    initiative: 8,
    growth: 6,
    abilities: [{ kind: 'morale_aura', value: 1 }, { kind: 'cleanse' }],
    lore: "Sa broderie de guerre dissipe l'hésitation comme on défait un nœud.",
  },
  {
    id: 'granit_t5',
    faction: 'granit',
    tier: 5,
    upgraded: false,
    name: 'Sanglier Cuirassé',
    namePlural: 'Sangliers Cuirassés',
    hp: 65,
    attack: 15,
    defense: 14,
    dmgMin: 11,
    dmgMax: 17,
    speed: 8,
    growth: 4,
    abilities: [{ kind: 'charge_bonus', perHex: 500, max: 3000 }],
    lore: "Bardé de plates aux couleurs du bourg ; on l'entend venir bien trop tard.",
  },
  {
    id: 'granit_t5_up',
    faction: 'granit',
    tier: 5,
    upgraded: true,
    upgradeOf: 'granit_t5',
    name: 'Verrat de Granit',
    namePlural: 'Verrats de Granit',
    hp: 76,
    attack: 17,
    defense: 16,
    dmgMin: 13,
    dmgMax: 20,
    speed: 9,
    initiative: 9,
    growth: 4,
    abilities: [
      { kind: 'charge_bonus', perHex: 600, max: 4000 },
      { kind: 'knockback', minHexes: 4 },
    ],
    lore: "Après une longue course, il ne bouscule pas : il déplace la ligne adverse.",
  },
  {
    id: 'granit_t6',
    faction: 'granit',
    tier: 6,
    upgraded: false,
    name: 'Chevalier du Forez',
    namePlural: 'Chevaliers du Forez',
    hp: 115,
    attack: 20,
    defense: 19,
    dmgMin: 20,
    dmgMax: 30,
    speed: 9,
    growth: 2,
    abilities: [{ kind: 'morale_aura', value: 1 }],
    lore: "Lance de frêne, housse grenat, serment prêté sur la borne des comtes.",
  },
  {
    id: 'granit_t6_up',
    faction: 'granit',
    tier: 6,
    upgraded: true,
    upgradeOf: 'granit_t6',
    name: 'Banneret de Cervières',
    namePlural: 'Bannerets de Cervières',
    hp: 132,
    attack: 23,
    defense: 21,
    dmgMin: 23,
    dmgMax: 34,
    speed: 10,
    initiative: 10,
    growth: 2,
    abilities: [
      { kind: 'morale_aura', value: 2 },
      { kind: 'charge_bonus', perHex: 400, max: 2000 },
    ],
    lore: "Son étendard se voit depuis le belvédère : toute l'armée relève la tête.",
  },
  {
    id: 'granit_t7',
    faction: 'granit',
    tier: 7,
    upgraded: false,
    name: 'Griffon de Pamole',
    namePlural: 'Griffons de Pamole',
    hp: 235,
    attack: 27,
    defense: 25,
    dmgMin: 38,
    dmgMax: 55,
    speed: 11,
    growth: 1,
    flying: true,
    abilities: [{ kind: 'retaliations', count: 2 }],
    lore: "Il niche dans les dalles fendues de Pierre Pamole et intercepte tout ce qui vole.",
  },
  {
    id: 'granit_t7_up',
    faction: 'granit',
    tier: 7,
    upgraded: true,
    upgradeOf: 'granit_t7',
    name: 'Griffon Couronné',
    namePlural: 'Griffons Couronnés',
    hp: 268,
    attack: 30,
    defense: 28,
    dmgMin: 43,
    dmgMax: 62,
    speed: 12,
    initiative: 12,
    growth: 1,
    flying: true,
    abilities: [{ kind: 'retaliations', count: 3 }],
    lore: "La couronne de plumes blanches n'est pas un ornement : c'est un droit de préséance.",
  },

  /* ───────────────────────── Ermitage des Bois Noirs ────────────────────── */
  {
    id: 'ermitage_t1',
    faction: 'ermitage',
    tier: 1,
    upgraded: false,
    name: 'Pèlerin',
    namePlural: 'Pèlerins',
    hp: 5,
    attack: 2,
    defense: 3,
    dmgMin: 1,
    dmgMax: 2,
    speed: 4,
    growth: 18,
    lore: "Bourdon de noisetier, coquille cousue, une foi qui ne discute pas la pente.",
  },
  {
    id: 'ermitage_t1_up',
    faction: 'ermitage',
    tier: 1,
    upgraded: true,
    upgradeOf: 'ermitage_t1',
    name: 'Pénitent Blanc',
    namePlural: 'Pénitents Blancs',
    hp: 7,
    attack: 3,
    defense: 4,
    dmgMin: 1,
    dmgMax: 3,
    speed: 5,
    initiative: 5,
    growth: 18,
    abilities: [{ kind: 'resurrect_after_win', bp: 1500 }],
    lore: "Après la bataille, on en retrouve toujours quelques-uns agenouillés, vivants.",
  },
  {
    id: 'ermitage_t2',
    faction: 'ermitage',
    tier: 2,
    upgraded: false,
    name: 'Chouette Hulotte',
    namePlural: 'Chouettes Hulottes',
    hp: 11,
    attack: 6,
    defense: 4,
    dmgMin: 2,
    dmgMax: 4,
    speed: 8,
    initiative: 9,
    growth: 12,
    flying: true,
    lore: "Vol sans bruit au ras des fougères ; elle voit la colonne avant la colonne.",
  },
  {
    id: 'ermitage_t2_up',
    faction: 'ermitage',
    tier: 2,
    upgraded: true,
    upgradeOf: 'ermitage_t2',
    name: 'Chouette Oraculaire',
    namePlural: 'Chouettes Oraculaires',
    hp: 14,
    attack: 7,
    defense: 5,
    dmgMin: 3,
    dmgMax: 5,
    speed: 9,
    initiative: 10,
    growth: 12,
    flying: true,
    abilities: [{ kind: 'reveal_fortune' }],
    lore: "Son cri annonce le sort avant qu'il tombe ; les veneurs apprennent à l'écouter.",
  },
  {
    id: 'ermitage_t3',
    faction: 'ermitage',
    tier: 3,
    upgraded: false,
    name: 'Loup des Bois Noirs',
    namePlural: 'Loups des Bois Noirs',
    hp: 22,
    attack: 9,
    defense: 7,
    dmgMin: 4,
    dmgMax: 7,
    speed: 8,
    growth: 8,
    lore: "La meute ne charge jamais de face ; elle attend le défaut de la ligne.",
  },
  {
    id: 'ermitage_t3_up',
    faction: 'ermitage',
    tier: 3,
    upgraded: true,
    upgradeOf: 'ermitage_t3',
    name: 'Loup des Brumes',
    namePlural: 'Loups des Brumes',
    hp: 26,
    attack: 11,
    defense: 8,
    dmgMin: 5,
    dmgMax: 8,
    speed: 9,
    initiative: 10,
    growth: 8,
    abilities: [{ kind: 'no_retaliation_flank' }],
    lore: "On ne le voit sortir de la brume qu'au moment où l'on saigne déjà.",
  },
  {
    id: 'ermitage_t4',
    faction: 'ermitage',
    tier: 4,
    upgraded: false,
    name: 'Veneur Sylvestre',
    namePlural: 'Veneurs Sylvestres',
    hp: 36,
    attack: 11,
    defense: 10,
    dmgMin: 7,
    dmgMax: 11,
    speed: 7,
    growth: 6,
    shooter: true,
    shots: 12,
    abilities: [{ kind: 'terrain_bonus', terrain: 'foret', attackBp: 1500, defenseBp: 1000 }],
    lore: "Arc de if, flèches à empennage de buse ; la futaie est sa portée utile.",
  },
  {
    id: 'ermitage_t4_up',
    faction: 'ermitage',
    tier: 4,
    upgraded: true,
    upgradeOf: 'ermitage_t4',
    name: 'Garde-Futaie',
    namePlural: 'Gardes-Futaies',
    hp: 42,
    attack: 13,
    defense: 12,
    dmgMin: 8,
    dmgMax: 13,
    speed: 8,
    initiative: 9,
    growth: 6,
    shooter: true,
    shots: 14,
    abilities: [
      { kind: 'stealth' },
      { kind: 'slow_on_hit', bp: 1000 },
      { kind: 'terrain_bonus', terrain: 'foret', attackBp: 2000, defenseBp: 1500 },
    ],
    lore: "Il compte les arbres comme d'autres comptent les écus, et il les fait payer.",
  },
  {
    id: 'ermitage_t5',
    faction: 'ermitage',
    tier: 5,
    upgraded: false,
    name: 'Cerf des Sources',
    namePlural: 'Cerfs des Sources',
    hp: 70,
    attack: 14,
    defense: 16,
    dmgMin: 11,
    dmgMax: 18,
    speed: 8,
    growth: 4,
    abilities: [{ kind: 'heal_aura', amount: 6 }],
    lore: "Là où il boit, l'eau reste claire jusqu'au printemps suivant.",
  },
  {
    id: 'ermitage_t5_up',
    faction: 'ermitage',
    tier: 5,
    upgraded: true,
    upgradeOf: 'ermitage_t5',
    name: 'Cerf Miraculeux',
    namePlural: 'Cerfs Miraculeux',
    hp: 82,
    attack: 16,
    defense: 18,
    dmgMin: 13,
    dmgMax: 21,
    speed: 9,
    initiative: 9,
    growth: 4,
    abilities: [{ kind: 'heal_aura', amount: 10 }, { kind: 'cleanse' }],
    lore: "Sa ramure porte, dit-on, la mémoire de toutes les sources consacrées.",
  },
  {
    id: 'ermitage_t6',
    faction: 'ermitage',
    tier: 6,
    upgraded: false,
    name: 'Colosse de Granite',
    namePlural: 'Colosses de Granite',
    hp: 130,
    attack: 18,
    defense: 23,
    dmgMin: 20,
    dmgMax: 29,
    speed: 6,
    initiative: 5,
    growth: 2,
    abilities: [{ kind: 'terrain_bonus', terrain: 'rocher', attackBp: 500, defenseBp: 2000 }],
    lore: "Une dalle debout que les racines ont fini par convaincre de marcher.",
  },
  {
    id: 'ermitage_t6_up',
    faction: 'ermitage',
    tier: 6,
    upgraded: true,
    upgradeOf: 'ermitage_t6',
    name: 'Colosse de Pamole',
    namePlural: 'Colosses de Pamole',
    hp: 150,
    attack: 21,
    defense: 26,
    dmgMin: 23,
    dmgMax: 33,
    speed: 7,
    initiative: 6,
    growth: 2,
    abilities: [
      { kind: 'terrain_bonus', terrain: 'rocher', attackBp: 800, defenseBp: 2500 },
      { kind: 'boulder', uses: 3, damage: 22 },
      { kind: 'siege_bonus', bp: 5000 },
    ],
    lore: "Il arrache un bloc à Pierre Pamole et le rend à la vallée, en ligne droite.",
  },
  {
    id: 'ermitage_t7',
    faction: 'ermitage',
    tier: 7,
    upgraded: false,
    name: 'Vouivre de la Durolle',
    namePlural: 'Vouivres de la Durolle',
    hp: 245,
    attack: 28,
    defense: 23,
    dmgMin: 40,
    dmgMax: 58,
    speed: 12,
    growth: 1,
    flying: true,
    abilities: [{ kind: 'poison', bp: 1000, turns: 3 }],
    lore: "Elle remonte la rivière la nuit ; l'escarboucle de son front éclaire les gorges.",
  },
  {
    id: 'ermitage_t7_up',
    faction: 'ermitage',
    tier: 7,
    upgraded: true,
    upgradeOf: 'ermitage_t7',
    name: 'Vouivre Couronnée',
    namePlural: 'Vouivres Couronnées',
    hp: 278,
    attack: 31,
    defense: 26,
    dmgMin: 45,
    dmgMax: 65,
    speed: 13,
    initiative: 13,
    growth: 1,
    flying: true,
    abilities: [
      { kind: 'poison', bp: 1500, turns: 3 },
      { kind: 'breath_line', length: 3 },
    ],
    lore: "Son souffle vert suit le fil de la vallée et ne s'arrête qu'au troisième rang.",
  },
];

/** Définitions de repli, indexées par identifiant. */
export const FALLBACK_CREATURES: Readonly<Record<CreatureId, CreatureDef>> = (() => {
  const map: Record<CreatureId, CreatureDef> = {};
  for (const s of SPECS) map[s.id] = build(s);
  return map;
})();

/** Identifiants connus de la table de repli, dans l'ordre canonique. */
export const FALLBACK_CREATURE_IDS: readonly CreatureId[] = SPECS.map((s) => s.id);
